# Generated by Django 3.0 on 2023-10-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expertise_level_required',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Pursuing Masters', 'Pursuing Masters'), ('Post Graduate', 'Post Graduate'), ('Pursing Phd', 'Pursuing PhD'), ('PhD', 'PhD')], max_length=100),
        ),
    ]
