# Generated by Django 3.0 on 2023-10-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231008_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Pursuing Masters', 'Pursuing Masters'), ('Post Graduate', 'Post Graduate'), ('Pursing Phd', 'Pursuing PhD'), ('PhD', 'PhD')], default='Undergraduate', max_length=100),
            preserve_default=False,
        ),
    ]
